#!/bin/bash
# Quick setup script for MongoDB integration

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  MongoDB Integration Setup Wizard     ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════╝${NC}\n"

# Check if MongoDB is installed
echo -e "${YELLOW}Checking MongoDB installation...${NC}"
if command -v mongod &> /dev/null; then
    echo -e "${GREEN}✓ MongoDB is installed${NC}"

    # Check if MongoDB is running
    if pgrep -x "mongod" > /dev/null; then
        echo -e "${GREEN}✓ MongoDB is running${NC}"
    else
        echo -e "${YELLOW}⚠ MongoDB is not running${NC}"
        echo -e "${YELLOW}Starting MongoDB...${NC}"
        if command -v brew &> /dev/null; then
            brew services start mongodb-community
            sleep 2
            if pgrep -x "mongod" > /dev/null; then
                echo -e "${GREEN}✓ MongoDB started${NC}"
            else
                echo -e "${RED}❌ Failed to start MongoDB${NC}"
                echo -e "${YELLOW}Try manually: brew services start mongodb-community${NC}"
            fi
        fi
    fi
else
    echo -e "${RED}❌ MongoDB is not installed${NC}"
    echo -e "${YELLOW}Would you like to install MongoDB now? (y/n)${NC}"
    read -r response
    if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
        if command -v brew &> /dev/null; then
            echo -e "${YELLOW}Installing MongoDB via Homebrew...${NC}"
            brew tap mongodb/brew
            brew install mongodb-community
            brew services start mongodb-community
            echo -e "${GREEN}✓ MongoDB installed and started${NC}"
        else
            echo -e "${RED}Homebrew not found. Please install MongoDB manually:${NC}"
            echo -e "${YELLOW}https://docs.mongodb.com/manual/installation/${NC}"
            exit 1
        fi
    else
        echo -e "${YELLOW}Skipping MongoDB installation${NC}"
        echo -e "${YELLOW}You can use MongoDB Atlas (cloud) instead${NC}"
    fi
fi

echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${YELLOW}Choose your MongoDB setup:${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "  ${GREEN}1${NC}) Local MongoDB (localhost)"
echo -e "  ${GREEN}2${NC}) MongoDB Atlas (cloud)"
echo -e "  ${GREEN}3${NC}) Custom MongoDB URI"
echo ""
echo -n "Enter your choice (1-3): "
read -r choice

case $choice in
    1)
        MONGODB_URI="mongodb://localhost:27017/"
        echo -e "${GREEN}✓ Using local MongoDB${NC}"
        ;;
    2)
        echo -e "${YELLOW}Enter your MongoDB Atlas connection string:${NC}"
        echo -e "${YELLOW}(e.g., mongodb+srv://username:password@cluster.mongodb.net/)${NC}"
        read -r MONGODB_URI
        ;;
    3)
        echo -e "${YELLOW}Enter your MongoDB URI:${NC}"
        read -r MONGODB_URI
        ;;
    *)
        echo -e "${RED}Invalid choice. Using local MongoDB as default.${NC}"
        MONGODB_URI="mongodb://localhost:27017/"
        ;;
esac

# Update mongo_config.sh
echo -e "\n${YELLOW}Updating configuration...${NC}"
cat > backend/mongo_config.sh << EOF
#!/bin/bash
# MongoDB Configuration
# Generated by setup_mongodb.sh on $(date)

export MONGODB_URI="$MONGODB_URI"
export USE_MONGODB="true"
export DATA_DIR="./data"

echo "MongoDB URI: \$MONGODB_URI"
echo "Use MongoDB: \$USE_MONGODB"
EOF

chmod +x backend/mongo_config.sh

echo -e "${GREEN}✓ Configuration saved to backend/mongo_config.sh${NC}"

# Test MongoDB connection
echo -e "\n${YELLOW}Testing MongoDB connection...${NC}"
cd backend
if /usr/bin/python3 -c "from pymongo import MongoClient; client = MongoClient('$MONGODB_URI', serverSelectionTimeoutMS=5000); client.admin.command('ping'); print('✓ Connection successful')" 2>/dev/null; then
    echo -e "${GREEN}✓ MongoDB connection test passed${NC}"
else
    echo -e "${RED}❌ MongoDB connection test failed${NC}"
    echo -e "${YELLOW}Please check your connection string and try again${NC}"
    exit 1
fi

cd ..

echo ""
echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║         Setup Complete! 🎉             ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════╝${NC}"
echo ""
echo -e "${GREEN}Next steps:${NC}"
echo -e "  1. Start the app: ${YELLOW}./start.sh${NC}"
echo -e "  2. Open browser: ${YELLOW}http://localhost:3000${NC}"
echo -e "  3. Go to Crawler page"
echo -e "  4. Toggle ON '${YELLOW}Save to MongoDB${NC}'"
echo -e "  5. Start crawling!"
echo ""
echo -e "${YELLOW}MongoDB URI: ${NC}$MONGODB_URI"
echo -e "${YELLOW}Database: ${NC}crawler_db"
echo -e "${YELLOW}Collection: ${NC}crawled_pages"
echo ""
echo -e "${GREEN}For more info, see: ${NC}MONGODB_GUIDE.md"
echo ""
